import Head from "next/head";
import { useState } from "react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { getSolvedCube, performAlg, type CubeData } from "cuber";
import CubeMesh from "../components/Cube";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const [cube, setCube] = useState<CubeData>(getSolvedCube());
  const [inputAlg, setInputAlg] = useState<string>("");

  const performAlgOnCube = (alg: string) => {
    setCube({ ...performAlg(cube, alg) });
  };

  return (
    <>
      <Head>
        <title>Mosaicube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center">
          <div className="h-[600px] w-[600px]">
            <Canvas
              camera={{
                fov: 60,
                aspect: 1,
                near: 0.1,
                far: 1000,
                position: [3.5, 3.5, 5.5],
              }}
            >
              <CubeMesh cube={cube} position={[0, 0, 0]} />
              <OrbitControls enablePan={false} enableZoom={false} />
            </Canvas>
          </div>
          <div className="flex items-center justify-center gap-4">
            <Input
              className="light px-4 py-2 text-black"
              value={inputAlg}
              onChange={(e) => setInputAlg(e.target.value)}
            />
            <Button onClick={() => performAlgOnCube(inputAlg)}>turn</Button>
          </div>
        </div>
        <Sidebar cube={cube} performAlgOnCube={performAlgOnCube} />
      </main>
    </>
  );
}
