import Head from "next/head";
import { useState } from "react";
import { Canvas } from "@react-three/fiber";
import { getSolvedCube, performAlg, type CubeData } from "cuber";
import CubeMesh from "../components/Cube";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const [cube, setCube] = useState<CubeData>(getSolvedCube());
  const [inputAlg, setInputAlg] = useState<string>("");

  return (
    <>
      <Head>
        <title>Mosaicube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center">
          <div className="h-[600px] w-[600px]">
            <Canvas
              camera={{
                fov: 60,
                aspect: 1,
                near: 0.1,
                far: 1000,
                position: [3.5, 3.5, 5.5],
              }}
            >
              <CubeMesh cube={cube} position={[0, 0, 0]} />
            </Canvas>
          </div>
          <div className="flex items-center justify-center gap-4">
            <input
              className="rounded-md bg-white px-4 py-2"
              value={inputAlg}
              onChange={(e) => setInputAlg(e.target.value)}
            />
            <button
              className="rounded-md bg-white px-4 py-2"
              onClick={() => setCube({ ...performAlg(cube, inputAlg) })}
            >
              turn
            </button>
          </div>
        </div>
        <Sidebar />
      </main>
    </>
  );
}
